version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-dev/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - e-commerce
    depends_on:
      - mysql
      - redis

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: e-commerce_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - e-commerce
    depends_on:
      - app

  # node:
  #   image: node:20-alpine
  #   container_name: e-commerce_node
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./:/var/www/html
  #   networks:
  #     - e-commerce
  #   tty: true
  #   stdin_open: true

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: e-commerce_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - e-commerce

  # Redis Service
  redis:
    image: redis:alpine
    container_name: e-commerce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - e-commerce

  # Queue Worker Service
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - e-commerce
    depends_on:
      - app
      - redis

  # Reverb WebSocket Service
  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce_reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8081:8080"
    volumes:
      - ./:/var/www
    networks:
      - e-commerce
    depends_on:
      - app
      - redis

  # Node/Vite Service
  vite:
    image: node:20-alpine
    container_name: e-commerce_vite
    restart: unless-stopped
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - e-commerce
    environment:
      - VITE_HOST=0.0.0.0

networks:
  e-commerce:
    driver: bridge

volumes:
  mysql_data:
    driver: local
